language: node_js
sudo: true
node_js: "12"
services: mongodb

before_script:
  - "npm run lint"

script:
  - "npm run test"
  - "chmod +x deploy-scripts/*"
  - "mkdir -p dist"
  - "./deploy-scripts/envvars.sh"
  - "zip -r dist/letmedraw.zip ./ -x '*node_modules*'"

deploy:
  - provider: s3
    bucket: letmedraw-backend-deploy
    region: us-east-1
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(develop|master)$
    local_dir: "./dist"
    upload_dir: "latest"
    skip_cleanup: true
  - provider: codedeploy
    bucket: "letmedraw-backend-deploy"
    region: us-east-1
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(develop|master)$
    key: latest/letmedraw.zip
    application: cd-letmedraw
    deployment_group: cd-dg-lmdws01

notifications:
  email:
    - alex_z9@outlook.com
